# This is a Docker image for running the tests.
# It should be pushed to registry.gitlab.com/sosy-lab/software/test-format/test
# and will be used by CI as declared in .gitlab-ci.yml.
#
# Commands for updating the image:
# docker build -t registry.gitlab.com/sosy-lab/software/test-suite-validator/test:python-3.7 - < test/Dockerfile.python-3.7
# docker push registry.gitlab.com/sosy-lab/software/test-suite-validator/test

FROM ubuntu:18.04

RUN apt update && apt install -y gcc-multilib g++-multilib lcov clang llvm python3.7 python3-pip git

RUN python3.7 -m pip install -U pip && python3.7 -m pip install \
  coverage \
  lxml \
  nose \
  pylint \
  black \
  benchexec \
  matplotlib
