# This is a Docker image for running the tests.
# It should be pushed to registry.gitlab.com/sosy-lab/software/test-format/test
# and will be used by CI as declared in .gitlab-ci.yml.
#
# Commands for updating the image:
# docker build -t registry.gitlab.com/sosy-lab/software/test-suite-validator/test:python-3.6 - < test/Dockerfile.python-3.6
# docker push registry.gitlab.com/sosy-lab/software/test-suite-validator/test

FROM ubuntu:18.04

RUN apt update && apt install -y gcc-multilib g++-multilib lcov clang llvm python3.6 python3.6-dev python3-pip

RUN python3.6 -m pip install -U pip && python3.6 -m pip install \
  coverage \
  lxml \
  nose \
  benchexec \
  matplotlib \
  numpy \
  pycparser
