# This is a Docker image for running the tests.
# It should be pushed to registry.gitlab.com/sosy-lab/software/test-format/test
# and will be used by CI as declared in .gitlab-ci.yml.
#
# Commands for updating the image:
# docker build -t registry.gitlab.com/sosy-lab/software/test-suite-validator/test:python-3.5 - < test/Dockerfile.python-3.5
# docker push registry.gitlab.com/sosy-lab/software/test-suite-validator/test

FROM python:3.5

RUN apt update && apt install -y gcc-multilib g++-multilib lcov clang

RUN pip install -U pip && pip install \
  coverage \
  lxml \
  nose \
  benchexec
