# To execute a job locally, install gitlab-runner (https://docs.gitlab.com/runner/install/)
# and run the following command:
# gitlab-runner exec docker --docker-privileged --docker-volumes /sys/fs/cgroup:/sys/fs/cgroup:rw --env CI_REGISTRY_IMAGE=registry.gitlab.com/sosy-lab/software/test-format <<JOB_NAME>>

image: ${CI_REGISTRY_IMAGE}/test:python-${PYTHON_VERSION}

variables:
    PYTHONPATH: "lib/"

.unit-tests: &unit-tests
  stage: test
  script:
    - ./setup.py nosetests
  artifacts:
    paths:
      - coverage.xml
      - cover

.integration-tests: &integration-tests
    stage: test
    script:
        - bin/testcov --verbose --test-suite test/suites/suite-invalid-unicode.zip test/test_invalid_unicode.c --goal contrib/goal_files/coverage-branches.prp --no-isolation

pylint:
  stage: test
  script:
    - pylint suite_validation
  variables:
    PYTHON_VERSION: '3.7'

check-format:
  stage: test
  script:
      - "black suite_validation && git diff -s --exit-code"
  variables:
    PYTHON_VERSION: '3.7'

check-archive:
    stage: test
    # Use docker image without dependencies installed
    # - these should be included in the archive and used correctly
    image: ${CI_REGISTRY_IMAGE}/test:plain
    # Archive testcov and run a simple test case on the archived version to check that it is working as expected
    script:
        - "./contrib/create_archive_testcov.sh"
        - cd /tmp && unzip "$CI_PROJECT_DIR/testcov.zip" && cd -
        - cd /tmp/testcov && ./bin/testcov --no-isolation --verbose --test-suite "$CI_PROJECT_DIR/test/suites/suite-valid.zip" --goal "$CI_PROJECT_DIR/contrib/goal_files/coverage-error-call.prp" "$CI_PROJECT_DIR/test/test_false.c"
    artifacts:
        paths:
            - testcov.zip

unit-tests:python-3.6:
  <<: *unit-tests
  variables:
    PYTHON_VERSION: '3.6'

unit-tests:python-3.7:
  <<: *unit-tests
  variables:
    PYTHON_VERSION: '3.7'

integration-tests:python-3.6:
  <<: *integration-tests
  variables:
    PYTHON_VERSION: '3.6'

integration-tests:python-3.7:
  <<: *integration-tests
  variables:
    PYTHON_VERSION: '3.7'

# 
# deploy-coverage:
#   stage: deploy
#   variables:
#     PYTHON_VERSION: '3.7'
#   before_script:
#     - pip install -e git+https://github.com/codacy/python-codacy-coverage.git#egg=codacy
#   script:
#     - python-codacy-coverage -r coverage.xml
#   dependencies:
#     - unit-tests:python-3.7
#   only:
#     refs:
#       - master
#     variables:
#       - $CODACY_PROJECT_TOKEN # required for job
#       - $CI_PROJECT_PATH == $PROJECT_PATH # not on forks
