# This file is part of TestCov,
# a robust test executor with reliable coverage measurement:
# https://gitlab.com/sosy-lab/software/test-suite-validator/
#
# SPDX-FileCopyrightText: 2019-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# To execute a job locally, install gitlab-runner (https://docs.gitlab.com/runner/install/)
# and run the following command:
# gitlab-runner exec docker --docker-privileged --docker-volumes /sys/fs/cgroup:/sys/fs/cgroup:rw --env CI_REGISTRY_IMAGE=registry.gitlab.com/sosy-lab/software/test-format <<JOB_NAME>>

image: ${CI_REGISTRY_IMAGE}/test:python-${PYTHON_VERSION}

variables:
    PYTHONPATH: "lib/"

.unit-tests: &unit-tests
  stage: test
  script:
    - ./setup.py nosetests
  artifacts:
    paths:
      - coverage.xml
      - cover

.integration-tests: &integration-tests
    stage: test
    script:
        - bin/testcov --verbose --test-suite test/suites/suite-invalid-unicode.zip test/test_invalid_unicode.c --goal contrib/goal_files/coverage-branches.prp --no-isolation
        - bin/testcov --verbose --test-suite test/suites/suite-invalid-unicode-test.zip test/test_invalid_unicode.c --goal contrib/goal_files/coverage-branches.prp --no-isolation
        - 'rm -rf output ; bin/testcov --verbose --test-suite test/suites/suite-valid.zip test/test_false_ReachError.c --goal contrib/goal_files/coverage-error-call.prp --no-isolation --no-stop-on-success && test $(ls output/info_files | wc -l) -eq 2'

pylint:
  stage: test
  script:
    - pylint suite_validation
  variables:
    PYTHON_VERSION: '3.8'

check-format:
  stage: test
  script:
      - "black --check suite_validation"
      - "clang-format -i suite_validation/harness.c && git diff -s --exit-code"
  variables:
    PYTHON_VERSION: '3.8'

check-archive:
    stage: test
    # Use docker image without dependencies installed
    # - these should be included in the archive and used correctly
    image: ${CI_REGISTRY_IMAGE}/test:plain
    # Archive testcov and run a simple test case on the archived version to check that it is working as expected
    script:
        - "./contrib/create_archive_testcov.sh"
        - cd /tmp && unzip "$CI_PROJECT_DIR"/testcov-*.zip && cd -
        - cd /tmp/testcov && ./bin/testcov --no-isolation --verbose --test-suite "$CI_PROJECT_DIR/test/suites/suite-valid.zip" --goal "$CI_PROJECT_DIR/contrib/goal_files/coverage-error-call.prp" "$CI_PROJECT_DIR/test/test_false_ReachError.c"
    artifacts:
        paths:
            - testcov-*.zip

unit-tests:python-3.6:
  <<: *unit-tests
  variables:
    PYTHON_VERSION: '3.6'

unit-tests:python-3.7:
  <<: *unit-tests
  variables:
    PYTHON_VERSION: '3.7'

unit-tests:python-3.8:
  <<: *unit-tests
  variables:
    PYTHON_VERSION: '3.8'

integration-tests:python-3.6:
  <<: *integration-tests
  variables:
    PYTHON_VERSION: '3.6'

integration-tests:python-3.7:
  <<: *integration-tests
  variables:
    PYTHON_VERSION: '3.7'

integration-tests:python-3.8:
  <<: *integration-tests
  variables:
    PYTHON_VERSION: '3.8'

# 
# deploy-coverage:
#   stage: deploy
#   variables:
#     PYTHON_VERSION: '3.8'
#   before_script:
#     - pip install -e git+https://github.com/codacy/python-codacy-coverage.git#egg=codacy
#   script:
#     - python-codacy-coverage -r coverage.xml
#   dependencies:
#     - unit-tests:python-3.8
#   only:
#     refs:
#       - master
#     variables:
#       - $CODACY_PROJECT_TOKEN # required for job
#       - $CI_PROJECT_PATH == $PROJECT_PATH # not on forks

reuse:
  stage: test
  dependencies: []
  needs: []
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
