# This file is part of TestCov,
# a robust test executor with reliable coverage measurement:
# https://gitlab.com/sosy-lab/software/test-suite-validator/
#
# SPDX-FileCopyrightText: 2019-2021 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

[metadata]
name = TestCov
version = attr: suite_validation._tool_info.__VERSION__
author = Dirk Beyer
author_email = dirk.beyer@sosy-lab.org
description = A container-based test-suite executor with coverage measurement
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/sosy-lab/software/test-suite-validator
project_urls =
  Changelog = https://gitlab.com/sosy-lab/software/test-suite-validator/-/blob/main/CHANGELOG.md
  Issue Tracker = https://gitlab.com/sosy-lab/software/test-suite-validator/-/issues
keywords =
  C
  testing
  test suite
  test-case generation
  verification
classifiers =
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Operating System :: POSIX :: Linux
  Programming Language :: Python :: 3 :: Only
  Topic :: Software Development :: Testing
license = Apache-2.0
license_files =
  LICENSES/Apache-2.0.txt

[options]
packages = suite_validation
install_requires =
  lxml>=4.0.0
  benchexec>=1.20
  pycparser>=2.19
  numpy>=1.15
tests_require =
  nose>=1.0
zip_safe = True
test_suite = nose.collector

[options.entry_points]
console_scripts =
  testcov = suite_validation:main

[pylint.REPORTS]
output-format = colorized
reports = yes

[pylint.'MESSAGES CONTROL']
good-names = a,db,e,es,f,i,j,k,ls,n,v
disable = missing-function-docstring,missing-docstring,line-too-long

[nosetests]
verbosity=1
with-coverage=1
cover-branches=1
cover-xml=1
cover-html=1
tests=suite_validation
cover-package=suite_validation
match=^(?:^|[\b_\.-])[Tt]est
