# This file is part of TestCov,
# a robust test executor with reliable coverage measurement:
# https://gitlab.com/sosy-lab/software/test-suite-validator/
#
# SPDX-FileCopyrightText: 2022 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# This is a Docker image for running the tests.
# It should be pushed to registry.gitlab.com/sosy-lab/software/test-suite-validator/test
# and will be used by CI as declared in .ci/gitlab-ci.yml.
#
# Commands for updating the image:
# docker build --pull -t registry.gitlab.com/sosy-lab/software/test-suite-validator/test:publish - < .ci/Dockerfile.publish
# docker push registry.gitlab.com/sosy-lab/software/test-suite-validator/test:publish

FROM python:3.9

RUN pip install \
    build \
    twine